project:
  type: website

website:
  title: "Simon Chiu"
  navbar:
    background: "#282D33"
    left:
      - text: "Data Analytics Projects"
        menu:
          - text: "Population Visual Analysis"
            href: "Data_Analytics_Projects/Population Visual Analysis/Population_Visual_Analysis.html"
          - text: "Fruad Detection"
            href: "Data_Analytics_Projects/Fraud Detection/Fraud_Detection.html"
      - text: "Quarto Tutorial Articles"
        menu:
          - text: "How to build a Quarto website"
            href: "Quarto_tutorial_articles/Quarto_Article1/Quarto_Article1.html"
          - text: "Custom Quarto Website"
            href: "Quarto_tutorial_articles/Quarto_Article2/Quarto_Article2.html"
      - text: "PowerBI Tutorial Articles"
        menu:
          - text: "How to import data from Jira"
            href: "PowerBI_tutorial_articles/Jira_with_PowerBI/Jira_with_PowerBI.html"
      - text: "Useful Application"
        menu:
          - text: "自動化宋詞練字本"
            href: "Useful Application/Automated Writing Template/Web_crawling_poems_from_Wiki.html"
    right:
      - icon: github
        href: https://github.com/simonchiu902/Personal-Website
      - icon: linkedin
        href: https://www.linkedin.com/in/shih-cheng-chiu-simon-183906163/
      - text: "Home"
        href: index.qmd

format:
  html:
    theme: journal
    css: styles.css
    toc: true

editor: visual

